# import = ["/home/majid/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
import = ["/home/majid/.config/alacritty/themes/themes/tokyo-night.toml"]

[env]
TERM = "tmux-256color"

[font]
size = 15

[font.bold]
family = "ComicShannsMono Nerd Font"

[font.bold_italic]
family = "ComicShannsMono Nerd Font"

[font.italic]
family = "ComicShannsMono Nerd Font"

[font.normal]
family = "ComicShannsMono Nerd Font"

[scrolling]
history = 5000

[window]
title = "Alacritty"
decorations= "None"

# [window.class]
# general = "Alacritty"
# instance = "Alacritty"

